[2024-12-26 16:27:24,974] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-26T16:26:00.327720+00:00 [None]>
[2024-12-26 16:27:24,985] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-26T16:26:00.327720+00:00 [None]>
[2024-12-26 16:27:24,986] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 16:27:24,987] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2024-12-26 16:27:24,987] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 16:27:24,998] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2024-12-26T16:26:00.327720+00:00
[2024-12-26 16:27:25,002] {standard_task_runner.py:52} INFO - Started process 230 to run task
[2024-12-26 16:27:25,004] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2024-12-26T16:26:00.327720+00:00', '--job-id', '20', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmp20uatczw', '--error-file', '/tmp/tmpkof13_1r']
[2024-12-26 16:27:25,005] {standard_task_runner.py:77} INFO - Job 20: Subtask task_zero
[2024-12-26 16:27:25,036] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2024-12-26T16:26:00.327720+00:00 [running]> on host d88713c29571
[2024-12-26 16:27:25,076] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2024-12-26T16:26:00.327720+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-26T16:26:00.327720+00:00
[2024-12-26 16:27:25,077] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-26 16:27:25,078] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2024-12-26 16:27:25,084] {subprocess.py:75} INFO - Output:
[2024-12-26 16:27:25,644] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2024-12-26 16:27:25,698] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2024-12-26 16:27:25,703] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2024-12-26 16:27:28,414] {subprocess.py:83} INFO - Command exited with return code 0
[2024-12-26 16:27:28,443] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20241226T162600, start_date=20241226T162724, end_date=20241226T162728
[2024-12-26 16:27:28,465] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-26 16:27:28,477] {local_task_job.py:151} INFO - Task exited with return code 0
