[2024-12-30 15:23:06,901] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-29T00:00:00+00:00 [queued]>
[2024-12-30 15:23:06,911] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-29T00:00:00+00:00 [queued]>
[2024-12-30 15:23:06,911] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 15:23:06,911] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2024-12-30 15:23:06,911] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-30 15:23:06,922] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2024-12-29T00:00:00+00:00
[2024-12-30 15:23:06,925] {standard_task_runner.py:52} INFO - Started process 61 to run task
[2024-12-30 15:23:06,928] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2024-12-29T00:00:00+00:00', '--job-id', '51', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmp7y8lqtg6', '--error-file', '/tmp/tmprv5ztoe9']
[2024-12-30 15:23:06,929] {standard_task_runner.py:77} INFO - Job 51: Subtask task_zero
[2024-12-30 15:23:06,966] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2024-12-29T00:00:00+00:00 [running]> on host d88713c29571
[2024-12-30 15:23:07,011] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2024-12-29T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-12-29T00:00:00+00:00
[2024-12-30 15:23:07,013] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-30 15:23:07,014] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2024-12-30 15:23:07,029] {subprocess.py:75} INFO - Output:
[2024-12-30 15:23:07,966] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2024-12-30 15:23:08,058] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2024-12-30 15:23:08,065] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2024-12-30 15:23:12,584] {subprocess.py:83} INFO - Command exited with return code 0
[2024-12-30 15:23:12,606] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20241229T000000, start_date=20241230T152306, end_date=20241230T152312
[2024-12-30 15:23:12,638] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-30 15:23:12,677] {local_task_job.py:151} INFO - Task exited with return code 0
