[2024-12-26 18:31:36,666] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-26T18:31:27.239331+00:00 [None]>
[2024-12-26 18:31:36,681] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2024-12-26T18:31:27.239331+00:00 [None]>
[2024-12-26 18:31:36,682] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 18:31:36,683] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2024-12-26 18:31:36,683] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2024-12-26 18:31:36,690] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2024-12-26T18:31:27.239331+00:00
[2024-12-26 18:31:36,697] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2024-12-26T18:31:27.239331+00:00', '--job-id', '28', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpxrdwut7n', '--error-file', '/tmp/tmpszjg9pe6']
[2024-12-26 18:31:36,694] {standard_task_runner.py:52} INFO - Started process 143 to run task
[2024-12-26 18:31:36,698] {standard_task_runner.py:77} INFO - Job 28: Subtask task_zero
[2024-12-26 18:31:36,736] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2024-12-26T18:31:27.239331+00:00 [running]> on host d88713c29571
[2024-12-26 18:31:36,779] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2024-12-26T18:31:27.239331+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-26T18:31:27.239331+00:00
[2024-12-26 18:31:36,780] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2024-12-26 18:31:36,781] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2024-12-26 18:31:36,787] {subprocess.py:75} INFO - Output:
[2024-12-26 18:31:37,404] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2024-12-26 18:31:37,454] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.12.3)
[2024-12-26 18:31:37,458] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2024-12-26 18:31:40,280] {subprocess.py:83} INFO - Command exited with return code 0
[2024-12-26 18:31:40,307] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20241226T183127, start_date=20241226T183136, end_date=20241226T183140
[2024-12-26 18:31:40,327] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-12-26 18:31:40,370] {local_task_job.py:151} INFO - Task exited with return code 0
